# Generated by Django 3.1.2 on 2020-12-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_reg_no', models.BigIntegerField()),
                ('User_reg_Date', models.DateField()),
                ('User_joining_Date', models.DateField()),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Date_Birth', models.DateField()),
                ('Address', models.CharField(max_length=50)),
                ('User_Photo', models.CharField(max_length=50)),
            ],
        ),
    ]
