# Generated by Django 3.1.2 on 2020-12-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp2', '0003_auto_20201221_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('User_Reg_No', models.BigIntegerField(primary_key=True, serialize=False)),
                ('User_Reg_Date', models.DateField()),
                ('User_Joining_Date', models.DateField()),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Date_Birth', models.DateField()),
                ('Mobile_No', models.BigIntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=10)),
                ('User_Photo', models.CharField(max_length=50)),
            ],
        ),
    ]
