# Generated by Django 3.1.2 on 2020-12-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Cred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Type', models.CharField(max_length=10)),
                ('User_Id', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('User_Reg_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Id', models.BigIntegerField()),
                ('Course_Name', models.CharField(max_length=30)),
                ('Course_Descrp', models.CharField(max_length=200)),
                ('Course_Duration', models.CharField(max_length=20)),
                ('Course_Logo', models.CharField(max_length=50)),
                ('Course_StartDate', models.DateField()),
                ('Course_EndDate', models.DateField()),
                ('Course_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user_info')),
            ],
        ),
    ]
