# Generated by Django 3.1.2 on 2020-12-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_course_info_user_cred'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='Gender',
            field=models.CharField(default='male', max_length=6),
            preserve_default=False,
        ),
    ]
