# Generated by Django 3.1.2 on 2020-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0006_user_info_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='Date_Birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='User_Photo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
