# Generated by Django 3.1.2 on 2021-01-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0008_auto_20210127_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Info',
        ),
    ]
