# Generated by Django 3.1.2 on 2021-01-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0010_course_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Info',
        ),
    ]
