# Generated by Django 3.1.2 on 2021-01-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0012_course_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_info',
            name='Course_Owner_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp2.user_info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_info',
            name='Course_Owner',
            field=models.CharField(max_length=30),
        ),
    ]
