# Generated by Django 3.1.2 on 2021-02-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0013_auto_20210128_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Student_Map',
            fields=[
                ('CSM_Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Assigned_Date', models.DateField(blank=True)),
                ('CSM_Status', models.CharField(blank=True, max_length=20)),
                ('Course_Progress', models.BigIntegerField()),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.course_info')),
                ('User_Reg_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user_info')),
            ],
        ),
    ]
