# Generated by Django 3.1.2 on 2021-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0014_course_student_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
