# Generated by Django 3.1.2 on 2021-03-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0015_user_info_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Student_Map',
        ),
    ]
