# Generated by Django 3.1.2 on 2021-03-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0022_auto_20210310_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='Mobile_No',
            field=models.CharField(max_length=30),
        ),
    ]
